name: CI

on:
  push:
    branches:
      - '**'  # This will run on push to any branch
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type checking
        run: npm run type-check

      - name: Run Jest tests
        run: npm test

      - name: Build Storybook
        run: npm run build-storybook

      - name: Run Storybook tests
        run: npx test-storybook
        env:
          NODE_OPTIONS: --no-experimental-fetch # Ensure stable fetch behavior 